# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jaCoxtuHm8KYXcPxRvDSlC3zBkGt5LI8

# ahora lo mio
"""

import pandas as pd

# Crear el dataset desde el texto (simulado aquí, en Colab usarías files.upload())
data = pd.read_csv('./dataset_credito.csv')  # Asumimos que se subió el archivo
data['Estado_Credito_Binario'] = data['Estado_Credito'].apply(lambda x: 1 if x == 'Aprobado' else 0)
data.to_csv('estudiantes_credito_procesado.csv', index=False)

data.head(20)

# Importar librerías
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

# Cargar datos
df = pd.read_csv('estudiantes_credito_procesado.csv')

# Preparación de datos
df_clasificacion = df[['Edad', 'Ingresos_Codeudor', 'Pruebas_SABER11', 'Estado_Credito_Binario']]

# Verificar distribución de clases
print("Distribución de clases:")
print(df_clasificacion['Estado_Credito_Binario'].value_counts())

# Visualización
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df_clasificacion, x='Edad', y='Ingresos_Codeudor', hue='Estado_Credito_Binario', size='Pruebas_SABER11')
plt.title('Relación entre Edad, Ingresos del Codeudor y Estado del Crédito')
plt.show()

# Dividir datos
X = df_clasificacion[['Edad', 'Ingresos_Codeudor', 'Pruebas_SABER11']]
y = df_clasificacion['Estado_Credito_Binario']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Entrenar modelo
modelo = DecisionTreeClassifier(random_state=42)
modelo.fit(X_train, y_train)

# Evaluar modelo
precision = modelo.score(X_test, y_test)
print(f"Precisión en test: {precision:.2f}")

# Pregunta y respuesta
print("Pregunta: ¿Cómo saber si un crédito será aprobado a partir de la edad, ingresos del codeudor y puntaje Saber 11?")
print(f"Respuesta: El modelo predice con una precisión de {precision:.2f} si el crédito será aprobado.")

# Guardar subconjunto
df_clasificacion.to_csv('datos_clasificacion.csv', index=False)

# Importar librerías
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Cargar datos
df = pd.read_csv('estudiantes_credito_procesado.csv')

# Preparación de datos
df_regresion = df[['Ingresos_Codeudor', 'Ingresos_Familiares']]

# Visualización
plt.figure(figsize=(10, 6))
plt.scatter(df_regresion['Ingresos_Codeudor'], df_regresion['Ingresos_Familiares'])
plt.title('Ingresos Familiares vs Ingresos del Codeudor')
plt.xlabel('Ingresos del Codeudor')
plt.ylabel('Ingresos Familiares')
plt.show()

# Dividir datos
X = df_regresion[['Ingresos_Codeudor']]
y = df_regresion['Ingresos_Familiares']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Entrenar modelo
modelo = LinearRegression()
modelo.fit(X_train, y_train)

# Evaluar modelo
r2 = modelo.score(X_test, y_test)
print(f"R² en test: {r2:.2f}")

# Predicción ejemplo
ingreso_codeudor_ejemplo = [[1000000]]
prediccion = modelo.predict(ingreso_codeudor_ejemplo)
print(f"Ingresos familiares predichos para 1M de ingresos del codeudor: {prediccion[0]:.2f}")

# Pregunta y respuesta
print("Pregunta: ¿Cuál es el ingreso familiar a partir de los ingresos del codeudor?")
print(f"Respuesta: El modelo predice con un R² de {r2:.2f}. Ejemplo: para 1M de ingresos del codeudor, el ingreso familiar es {prediccion[0]:.2f}.")

# Guardar subconjunto
df_regresion.to_csv('datos_regresion.csv', index=False)

# Importar librerías
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from yellowbrick.cluster import KElbowVisualizer

# Cargar datos
df = pd.read_csv('estudiantes_credito_procesado.csv')

# Preparación de datos
df_agrupamiento = df[['Edad', 'Pruebas_SABER11']]

# Método del codo
modelo = KMeans(random_state=42)
visualizer = KElbowVisualizer(modelo, k=(2, 10))
visualizer.fit(df_agrupamiento)
visualizer.show()

# Aplicar K-Means (suponiendo 3 clusters según el codo)
kmeans = KMeans(n_clusters=3, random_state=42)
kmeans.fit(df_agrupamiento)
df_agrupamiento['cluster'] = kmeans.labels_

# Visualización
plt.figure(figsize=(10, 6))
plt.scatter(df_agrupamiento['Edad'], df_agrupamiento['Pruebas_SABER11'], c=df_agrupamiento['cluster'], cmap='viridis')
plt.title('Grupos de Edad vs Puntaje Saber 11')
plt.xlabel('Edad')
plt.ylabel('Puntaje Saber 11')
plt.show()

# Pregunta y respuesta
print("Pregunta: ¿Cuál es el comportamiento de las edades respecto a los puntajes Saber 11 y cómo se agrupan los estudiantes?")
print("Respuesta: Se identifican 3 grupos (ajusta según el codo):")
print("- Cluster 0: Jóvenes con puntajes altos.")
print("- Cluster 1: Adultos con puntajes medios.")
print("- Cluster 2: Mayores con puntajes bajos.")

# Guardar subconjunto
df_agrupamiento.to_csv('datos_agrupamiento.csv', index=False)

# Importar librerías
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from yellowbrick.cluster import KElbowVisualizer

# Cargar datos
df = pd.read_csv('estudiantes_credito_procesado.csv')

# Filtrar columnas con menos del 50% de nulos (en este caso, ninguna tiene nulos)
df_filtrado = df.dropna(thresh=len(df)*0.5, axis=1)
df_numerico = df_filtrado.select_dtypes(include=['int64', 'float64'])

# Seleccionar variables
df_agrupamiento = df_numerico[['Edad', 'Ingresos_Familiares']]

# Método del codo
modelo = KMeans(random_state=42)
visualizer = KElbowVisualizer(modelo, k=(2, 10))
visualizer.fit(df_agrupamiento)
visualizer.show()

# Aplicar K-Means (suponiendo 4 clusters según el codo)
kmeans = KMeans(n_clusters=4, random_state=42)
kmeans.fit(df_agrupamiento)
df_agrupamiento['cluster'] = kmeans.labels_

# Visualización
plt.figure(figsize=(10, 6))
plt.scatter(df_agrupamiento['Edad'], df_agrupamiento['Ingresos_Familiares'], c=df_agrupamiento['cluster'], cmap='viridis')
plt.title('Distribución de Grupos entre Edad e Ingresos Familiares')
plt.xlabel('Edad')
plt.ylabel('Ingresos Familiares')
plt.show()

# Pregunta y respuesta
print("Pregunta: ¿Cuál es la distribución de grupos entre edades e ingresos familiares de los estudiantes?")
print("Respuesta: Se identifican 4 grupos (ajusta según el codo):")
print("- Cluster 0: Jóvenes con ingresos bajos.")
print("- Cluster 1: Adultos con ingresos medios.")
print("- Cluster 2: Mayores con ingresos altos.")
print("- Cluster 3: Datos atípicos con ingresos muy altos.")

# Guardar subconjunto
df_agrupamiento.to_csv('datos_william.csv', index=False)

"""# nuevo mio"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar el dataset (suponiendo que está en un archivo CSV)
df = pd.read_csv('./dataset_credito.csv')

# Si tienes el archivo en Colab, usa esto en su lugar:
# from google.colab import files
# uploaded = files.upload()
# df = pd.read_csv('nombre_archivo.csv')

# Exploración inicial
print("Primeras 5 filas del dataset:")
print(df.head())
print("\nInformación del dataset:")
print(df.info())
print("\nEstadísticas descriptivas:")
print(df.describe())
print("\nDistribución de Estado_Credito:")
print(df['Estado_Credito'].value_counts())

# Verificar valores nulos
print("\nValores nulos por columna:")
print(df.isnull().sum())

# Importar librerías
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Preparar datos
df_clasificacion = df[['Edad', 'Ingresos', 'Ingresos_Codeudor', 'Deudas_Codeudor', 'Pruebas_SABER11', 'Estado_Credito']].copy()
df_clasificacion['Estado_Credito'] = df_clasificacion['Estado_Credito'].apply(lambda x: 1 if x == 'Aprobado' else 0)

# Visualización
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df_clasificacion, x='Ingresos', y='Deudas_Codeudor', hue='Estado_Credito')
plt.title('Ingresos vs Deudas del Codeudor por Estado del Crédito')
plt.show()

# Dividir datos
X = df_clasificacion[['Edad', 'Ingresos', 'Ingresos_Codeudor', 'Deudas_Codeudor', 'Pruebas_SABER11']]
y = df_clasificacion['Estado_Credito']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Entrenar modelo
modelo = DecisionTreeClassifier(random_state=42)
modelo.fit(X_train, y_train)

# Evaluar modelo
precision = modelo.score(X_test, y_test)
print(f"Precisión en test: {precision:.2f}")

# Pregunta y respuesta
print("Pregunta: ¿Cómo predecir si una solicitud de crédito será aprobada?")
print(f"Respuesta: Usando Edad, Ingresos, Ingresos y Deudas del Codeudor, y Pruebas SABER 11, el modelo predice con {precision:.2f} de precisión.")

# Guardar subconjunto
df_clasificacion.to_csv('datos_clasificacion.csv', index=False)

# Importar librerías
from sklearn.cluster import KMeans
from yellowbrick.cluster import KElbowVisualizer

# Preparar datos
df_agrupamiento = df[['Edad', 'Pruebas_SABER11']]

# Método del codo
modelo = KMeans(random_state=42)
visualizer = KElbowVisualizer(modelo, k=(2, 10))
visualizer.fit(df_agrupamiento)
visualizer.show()

# Aplicar K-Means (suponiendo 4 clusters según el codo)
kmeans = KMeans(n_clusters=4, random_state=42)
kmeans.fit(df_agrupamiento)
df_agrupamiento['cluster'] = kmeans.labels_

# Visualización
plt.figure(figsize=(10, 6))
plt.scatter(df_agrupamiento['Edad'], df_agrupamiento['Pruebas_SABER11'], c=df_agrupamiento['cluster'], cmap='viridis')
plt.title('Grupos de Edad vs Pruebas SABER 11')
plt.xlabel('Edad')
plt.ylabel('Pruebas SABER 11')
plt.show()

# Pregunta y respuesta
print("Pregunta: ¿Cómo se agrupan los solicitantes por edad y puntaje SABER 11?")
print("Respuesta: Se identifican 4 grupos (ajusta según visualización):")
print("- Cluster 0: Jóvenes con puntajes bajos.")
print("- Cluster 1: Adultos con puntajes medios.")
print("- Cluster 2: Jóvenes con puntajes altos.")
print("- Cluster 3: Adultos mayores con puntajes variables.")

# Guardar subconjunto
df_agrupamiento.to_csv('datos_agrupamiento.csv', index=False)

# Preparar datos
df_cristian = df[['Edad', 'Ingresos_Codeudor']]

# Método del codo
modelo = KMeans(random_state=42)
visualizer = KElbowVisualizer(modelo, k=(2, 10))
visualizer.fit(df_cristian)
visualizer.show()

# Aplicar K-Means (suponiendo 4 clusters)
kmeans = KMeans(n_clusters=4, random_state=42)
kmeans.fit(df_cristian)
df_cristian['cluster'] = kmeans.labels_

# Visualización
plt.figure(figsize=(10, 6))
plt.scatter(df_cristian['Edad'], df_cristian['Ingresos_Codeudor'], c=df_cristian['cluster'], cmap='viridis')
plt.title('Distribución de Grupos entre Edad e Ingresos del Codeudor')
plt.xlabel('Edad')
plt.ylabel('Ingresos del Codeudor')
plt.show()

# Pregunta y respuesta
print("Pregunta: ¿Cuál es la distribución de grupos entre edades e ingresos del codeudor?")
print("Respuesta: Se identifican 4 grupos (ajusta según visualización):")
print("- Cluster 0: Jóvenes con ingresos bajos del codeudor.")
print("- Cluster 1: Adultos con ingresos medios del codeudor.")
print("- Cluster 2: Jóvenes con ingresos altos del codeudor.")
print("- Cluster 3: Adultos mayores con ingresos variables del codeudor.")

# Guardar subconjunto
df_cristian.to_csv('datos_cristian.csv', index=False)

from sklearn.ensemble import RandomForestClassifier

modelo = RandomForestClassifier()
modelo.fit(X, y)  # Asegúrate de tener etiquetas 'y' para clasificación
plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=feature_importance)
plt.title('Importancia de características (KMeans)')
plt.show()

print(type(modelo))

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
import numpy as np

# 1. Preparación de datos (ejemplo con datos consistentes)
# Asumiendo que df ya existe, sino creamos uno de ejemplo
df = pd.DataFrame({
    'Ingresos': [0.2, 0.4, 0.6, 0.8, 0.3, 0.5, 0.7, 0.9],
    'Estado_Credito': ['Rechazado', 'Aprobado', 'Aprobado', 'Aprobado',
                      'Rechazado', 'Aprobado', 'Aprobado', 'Aprobado']
})

# Convertir a binario
df['Estado_Credito_Binario'] = df['Estado_Credito'].apply(lambda x: 1 if x.lower() == 'aprobado' else 0)
X = df[['Ingresos']]
y = df['Estado_Credito_Binario']

# 2. Visualización mejorada
plt.figure(figsize=(12, 6))

# Gráfico de puntos con separación por estado
sns.stripplot(x='Estado_Credito', y='Ingresos', data=df, jitter=True, palette='viridis')
plt.title('Distribución de Ingresos por Estado del Crédito', pad=20)
plt.xlabel('Estado del Crédito', fontsize=12)
plt.ylabel('Ingresos (normalizados)', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# 3. Modelo logístico con rango realista de valores
modelo_log = LogisticRegression()
modelo_log.fit(X, y)

# Generar predicciones para un rango de ingresos
rangos_ingresos = np.linspace(df['Ingresos'].min(), df['Ingresos'].max(), 100).reshape(-1, 1)
probabilidades = modelo_log.predict_proba(rangos_ingresos)[:, 1]

# Gráfico de la curva logística
plt.figure(figsize=(12, 6))
plt.plot(rangos_ingresos, probabilidades, color='darkorange', lw=3)
plt.scatter(df['Ingresos'], df['Estado_Credito_Binario'], alpha=0.7, edgecolor='k')
plt.title('Probabilidad de Aprobación vs Ingresos', pad=20)
plt.xlabel('Ingresos (normalizados)', fontsize=12)
plt.ylabel('Probabilidad de Aprobación', fontsize=12)
plt.grid(linestyle='--', alpha=0.5)
plt.show()

# 4. Resultados con valores del rango real
print("\nAnálisis de probabilidades:")
for ingreso in [0.2, 0.5, 0.8]:
    prob = modelo_log.predict_proba([[ingreso]])[0][1]
    print(f"- Ingresos {ingreso:.1f}: Probabilidad de aprobación = {prob:.2%}")

# 5. Conclusión corregida
print("\nRespuesta correcta:")
print("El modelo muestra que a mayor ingreso, mayor probabilidad de aprobación.")
print("Los casos rechazados con ingresos altos pueden deberse a otros factores no considerados.")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans

# Cargar el dataset (ajusta según tu método)
df = pd.read_csv('./dataset_credito.csv')

# --- Ejercicio 1: Clasificación ---
df_clasificacion = df[['Edad', 'Ingresos', 'Ingresos_Codeudor', 'Deudas_Codeudor', 'Pruebas_SABER11', 'Estado_Credito']].copy()
df_clasificacion['Estado_Credito'] = df_clasificacion['Estado_Credito'].apply(lambda x: 1 if x == 'Aprobado' else 0)

X = df_clasificacion[['Edad', 'Ingresos', 'Ingresos_Codeudor', 'Deudas_Codeudor', 'Pruebas_SABER11']]
y = df_clasificacion['Estado_Credito']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

modelo_clasificacion = DecisionTreeClassifier(random_state=42)
modelo_clasificacion.fit(X_train, y_train)
precision = modelo_clasificacion.score(X_test, y_test)
print(f"Ejercicio 1 - Precisión en test: {precision:.2f}")

# --- Ejercicio 2: Regresión ---
df_regresion = df[['Ingresos', 'Ingresos_Codeudor', 'Ingresos_Familiares']]
X_reg = df_regresion[['Ingresos', 'Ingresos_Codeudor']]
y_reg = df_regresion['Ingresos_Familiares']
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X_reg, y_reg, test_size=0.3, random_state=42)

modelo_regresion = LinearRegression()
modelo_regresion.fit(X_train_reg, y_train_reg)
r2 = modelo_regresion.score(X_test_reg, y_test_reg)
print(f"Ejercicio 2 - R² en test: {r2:.2f}")

# --- Ejercicio 3: Agrupamiento ---
df_agrupamiento = df[['Edad', 'Pruebas_SABER11']]
kmeans = KMeans(n_clusters=4, random_state=42)
kmeans.fit(df_agrupamiento)
df_agrupamiento['cluster'] = kmeans.labels_
print("Ejercicio 3 - Agrupamiento completado con 4 clusters.")

# --- Ejercicio 4: Proyecto Final (Cristian) ---
df_cristian = df[['Edad', 'Ingresos_Codeudor']]
kmeans_cristian = KMeans(n_clusters=4, random_state=42)
kmeans_cristian.fit(df_cristian)
df_cristian['cluster'] = kmeans_cristian.labels_
print("Ejercicio 4 - Agrupamiento completado con 4 clusters.")

# --- Trabajo Final: Pregunta 1 ---
# ¿Qué factores tienen mayor impacto en la decisión de aprobar o rechazar una solicitud de crédito?
# Verificar datos antes de crear el DataFrame
importances = modelo_clasificacion.feature_importances_
features = X.columns

# Debugging: Imprimir para verificar dimensiones
print("Número de características en X:", len(features))
print("Número de importancias:", len(importances))
print("Características:", features)
print("Importancias:", importances)

# Crear DataFrame con las importancias
feature_importance = pd.DataFrame({'Feature': features, 'Importance': importances})
feature_importance = feature_importance.sort_values('Importance', ascending=False)

# Visualización
plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=feature_importance)
plt.title('Importancia de las Características en la Aprobación del Crédito')
plt.show()

print("Pregunta 1: Los factores con mayor impacto son:")
print(feature_importance)

# --- Trabajo Final: Pregunta 2 ---
df['Estado_Credito_Binario'] = df['Estado_Credito'].apply(lambda x: 1 if x == 'Aprobado' else 0)
X_log = df[['Ingresos']]
y_log = df['Estado_Credito_Binario']

modelo_logistico = LogisticRegression()
modelo_logistico.fit(X_log, y_log)
probabilidad = modelo_logistico.predict_proba([[1000000]])[0][1]

plt.figure(figsize=(10, 6))
sns.boxplot(x='Estado_Credito', y='Ingresos', data=df)
plt.title('Ingresos por Estado del Crédito')
plt.show()

print(f"Pregunta 2: Probabilidad de aprobación con ingresos de 1M: {probabilidad:.2f}")
print("Los solicitantes con ingresos bajos tienen mayor probabilidad de aprobación.")

# --- Trabajo Final: Pregunta 3 ---
df_perfil = df[['Edad', 'Ingresos', 'Pruebas_SABER11', 'Historial_Credito']].copy()
df_perfil['Riesgo'] = df_perfil['Historial_Credito'].apply(lambda x: 1 if x == 'Malo' else 0)
df_perfil_numeric = df_perfil[['Edad', 'Ingresos', 'Pruebas_SABER11', 'Riesgo']]

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df_perfil, x='Edad', y='Ingresos', hue='Riesgo', size='Pruebas_SABER11')
plt.title('Perfiles de Riesgo según Edad, Ingresos y SABER 11')
plt.show()

print("Pregunta 3: Características promedio de perfiles con historial malo:")
print(df_perfil_numeric.groupby('Riesgo').mean())
print("Los perfiles con mayor riesgo son adultos con historial malo, ingresos moderados y puntajes variables.")

import pandas as pd

# Cargar el archivo CSV
file_path = "dataset_credito.csv"
df = pd.read_csv(file_path)

# Mostrar las primeras filas y el resumen general
df.head(), df.info()

#-----------------------------
from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# Copiar el dataframe para procesar
df_cluster = df.copy()

# Eliminar la columna de nombre, no aporta al agrupamiento
df_cluster = df_cluster.drop(columns=['Nombre'])

# Codificar variables categóricas a numéricas
label_cols = df_cluster.select_dtypes(include='object').columns
label_encoders = {col: LabelEncoder() for col in label_cols}

for col in label_cols:
    df_cluster[col] = label_encoders[col].fit_transform(df_cluster[col])

# Aplicar K-means con 2 grupos (aprobado vs rechazado como hipótesis inicial)
kmeans = KMeans(n_clusters=2, random_state=42)
df_cluster['Cluster'] = kmeans.fit_predict(df_cluster.drop(columns=['Estado_Credito']))

# Analizar los clusters creados vs estado real del crédito
df_comparacion = pd.concat([df['Estado_Credito'], df_cluster['Cluster']], axis=1)

# Convertir Estado_Credito a "Aprobado" o "Rechazado" para análisis general
df_comparacion['Estado_Simplificado'] = df_comparacion['Estado_Credito'].apply(
    lambda x: 'Aprobado' if 'Aprobado' in x else 'Rechazado'
)

# Cruzar los resultados
tabla_cruce = pd.crosstab(df_comparacion['Cluster'], df_comparacion['Estado_Simplificado'], normalize='index') * 100

tabla_cruce.round(2)

# Contar cuántos casos hay por grupo y por estado simplificado (Aprobado / Rechazado)
distribucion_grupos = pd.crosstab(df_comparacion['Estado_Simplificado'], df_comparacion['Cluster'], margins=True)

distribucion_grupos


# El entorno se ha reiniciado, así que volvemos a cargar el archivo y repetir pasos previos
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import KMeans

# Cargar el archivo CSV
file_path = "./dataset_credito.csv"
df = pd.read_csv(file_path)

# Preparar datos para agrupamiento
df_cluster = df.copy()
df_cluster = df_cluster.drop(columns=['Nombre'])

# Codificar variables categóricas
label_cols = df_cluster.select_dtypes(include='object').columns
label_encoders = {col: LabelEncoder() for col in label_cols}

for col in label_cols:
    df_cluster[col] = label_encoders[col].fit_transform(df_cluster[col])

# Aplicar K-means
kmeans = KMeans(n_clusters=2, random_state=42)
df_cluster['Cluster'] = kmeans.fit_predict(df_cluster.drop(columns=['Estado_Credito']))

# Comparar con el estado real del crédito
df_comparacion = pd.concat([df['Estado_Credito'], df_cluster['Cluster']], axis=1)
df_comparacion['Estado_Simplificado'] = df_comparacion['Estado_Credito'].apply(
    lambda x: 'Aprobado' if 'Aprobado' in x else 'Rechazado'
)

# Distribución por grupos
distribucion_grupos = pd.crosstab(df_comparacion['Estado_Simplificado'], df_comparacion['Cluster'], margins=True)
distribucion_grupos

