# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vcUmOwxeefMIJspBZX5uCyQKI2CxZpW-
"""

# Importar bibliotecas necesarias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
from sklearn.ensemble import RandomForestClassifier

# Cargar el archivo CSV (subir 'creditos_estudiantiles.csv' a Colab primero)
df = pd.read_csv('./dataset_credito.csv')

# --- Información inicial ---
print("Información del DataFrame:")
df.info()
print("\nEstadísticas descriptivas de variables numéricas:")
print(df.describe())
print("\nPrimeras 5 filas:")
print(df.head())

# --- Limpieza de datos ---
# Separar 'Estado_Credito' en 'Resultado' y 'Motivo'
df['Resultado'] = df['Estado_Credito'].apply(lambda x: 'Aprobado' if x == 'Aprobado' else 'Rechazado')
df['Motivo'] = df['Estado_Credito'].apply(lambda x: x.split('(')[-1].strip(')') if 'Rechazado' in x else 'Aprobado')
df = df.drop('Estado_Credito', axis=1)

# Convertir categóricas a numéricas con one-hot encoding
categorical_cols = ['SISBEN', 'Titulo_Universitario', 'Codeudor', 'Programa', 'Historial_Credito']
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# Eliminar 'Nombre' (no aporta al análisis)
df_encoded = df_encoded.drop('Nombre', axis=1)

print("\nDataFrame limpio (primeras 5 filas):")
print(df_encoded.head())

# --- Análisis exploratorio detallado ---
# 1. Distribución de 'Resultado'
plt.figure(figsize=(8, 5))
sns.countplot(x='Resultado', data=df_encoded)
plt.title('Distribución de Resultado (Aprobado vs Rechazado)')
plt.xlabel('Resultado')
plt.ylabel('Cantidad')
plt.show()
print("\nConteo de Resultado:")
print(df_encoded['Resultado'].value_counts())

# 2. Distribución de 'Edad' por 'Resultado'
plt.figure(figsize=(10, 6))
sns.boxplot(x='Resultado', y='Edad', data=df_encoded)
plt.title('Distribución de Edad por Resultado')
plt.show()
print("\nEstadísticas de Edad por Resultado:")
print(df.groupby('Resultado')['Edad'].describe())

# 3. Relación 'Pruebas_SABER11' y 'Resultado'
plt.figure(figsize=(10, 6))
sns.boxplot(x='Resultado', y='Pruebas_SABER11', data=df_encoded)
plt.title('Puntaje Saber 11 por Resultado')
plt.show()
print("\nEstadísticas de Pruebas_SABER11 por Resultado:")
print(df.groupby('Resultado')['Pruebas_SABER11'].describe())

# 4. Distribución de 'Ingresos_Codeudor' y 'Deudas_Codeudor'
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
sns.histplot(df['Ingresos_Codeudor'], bins=30, kde=True)
plt.title('Distribución de Ingresos del Codeudor')
plt.subplot(1, 2, 2)
sns.histplot(df['Deudas_Codeudor'], bins=30, kde=True)
plt.title('Distribución de Deudas del Codeudor')
plt.tight_layout()
plt.show()

# 5. Motivos de rechazo
plt.figure(figsize=(12, 8))
sns.countplot(y='Motivo', data=df, order=df['Motivo'].value_counts().index)
plt.title('Motivos de Rechazo/Aprobación')
plt.xlabel('Cantidad')
plt.ylabel('Motivo')
plt.show()
print("\nConteo de Motivos:")
print(df['Motivo'].value_counts())

# 6. Relación entre 'SISBEN' y 'Resultado'
plt.figure(figsize=(12, 6))
sns.countplot(x='SISBEN', hue='Resultado', data=df)
plt.title('Resultado por Nivel SISBEN')
plt.xticks(rotation=45)
plt.show()

# 7. Relación entre 'Programa' y 'Resultado'
plt.figure(figsize=(12, 6))
sns.countplot(x='Programa', hue='Resultado', data=df)
plt.title('Resultado por Programa Académico')
plt.xticks(rotation=45)
plt.show()

# 8. Correlación entre variables numéricas
numeric_cols = ['Edad', 'Ingresos', 'Ingresos_Codeudor', 'Deudas_Codeudor', 'Pruebas_SABER11', 'Ingresos_Familiares']
plt.figure(figsize=(10, 8))
sns.heatmap(df_encoded[numeric_cols].corr(), annot=True, cmap='coolwarm', vmin=-1, vmax=1)
plt.title('Matriz de Correlación de Variables Numéricas')
plt.show()

# --- Preprocesamiento para modelado ---
X = df_encoded.drop(['Resultado', 'Motivo'], axis=1)  # Características
y = df_encoded['Resultado'].map({'Aprobado': 1, 'Rechazado': 0})  # Objetivo binario

# Dividir en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Normalizar variables numéricas
scaler = StandardScaler()
X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

# --- Modelado detallado ---
# 1. Regresión Logística
log_model = LogisticRegression(class_weight='balanced', random_state=42)
log_model.fit(X_train, y_train)
y_pred_log = log_model.predict(X_test)

# 2. Random Forest (para comparar)
rf_model = RandomForestClassifier(class_weight='balanced', n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

# --- Evaluación de modelos ---
# Reporte de clasificación
print("\nReporte de Clasificación - Regresión Logística:")
print(classification_report(y_test, y_pred_log))
print("\nReporte de Clasificación - Random Forest:")
print(classification_report(y_test, y_pred_rf))

# Matriz de confusión
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
sns.heatmap(confusion_matrix(y_test, y_pred_log), annot=True, fmt='d', cmap='Blues')
plt.title('Matriz de Confusión - Regresión Logística')
plt.xlabel('Predicho')
plt.ylabel('Real')
plt.subplot(1, 2, 2)
sns.heatmap(confusion_matrix(y_test, y_pred_rf), annot=True, fmt='d', cmap='Blues')
plt.title('Matriz de Confusión - Random Forest')
plt.xlabel('Predicho')
plt.ylabel('Real')
plt.tight_layout()
plt.show()

# Curva ROC
plt.figure(figsize=(10, 6))
# Regresión Logística
fpr_log, tpr_log, _ = roc_curve(y_test, log_model.predict_proba(X_test)[:, 1])
roc_auc_log = auc(fpr_log, tpr_log)
plt.plot(fpr_log, tpr_log, label=f'Regresión Logística (AUC = {roc_auc_log:.2f})')
# Random Forest
fpr_rf, tpr_rf, _ = roc_curve(y_test, rf_model.predict_proba(X_test)[:, 1])
roc_auc_rf = auc(fpr_rf, tpr_rf)
plt.plot(fpr_rf, tpr_rf, label=f'Random Forest (AUC = {roc_auc_rf:.2f})')
plt.plot([0, 1], [0, 1], 'k--')
plt.title('Curva ROC')
plt.xlabel('Tasa de Falsos Positivos')
plt.ylabel('Tasa de Verdaderos Positivos')
plt.legend()
plt.show()

# Validación cruzada
log_cv_scores = cross_val_score(log_model, X, y, cv=5, scoring='f1')
rf_cv_scores = cross_val_score(rf_model, X, y, cv=5, scoring='f1')
print("\nF1-Score promedio (validación cruzada) - Regresión Logística:", log_cv_scores.mean())
print("F1-Score promedio (validación cruzada) - Random Forest:", rf_cv_scores.mean())

# Importancia de características (Random Forest)
importances = rf_model.feature_importances_
feature_names = X.columns
feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances})
feature_importance_df = feature_importance_df.sort_values('Importance', ascending=False)

plt.figure(figsize=(12, 6))
sns.barplot(x='Importance', y='Feature', data=feature_importance_df.head(10))
plt.title('Top 10 Características más Importantes (Random Forest)')
plt.show()

# Importar bibliotecas necesarias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
from sklearn.ensemble import RandomForestClassifier

# Cargar el archivo CSV (subir 'creditos_estudiantiles.csv' a Colab primero)
df = pd.read_csv('./dataset_credito.csv')

# --- Información inicial ---
print("Información del DataFrame:")
df.info()
print("\nEstadísticas descriptivas de variables numéricas:")
print(df.describe())
print("\nPrimeras 5 filas:")
print(df.head())

# --- Limpieza de datos ---
# Separar 'Estado_Credito' en 'Resultado' y 'Motivo'
df['Resultado'] = df['Estado_Credito'].apply(lambda x: 'Aprobado' if x == 'Aprobado' else 'Rechazado')
df['Motivo'] = df['Estado_Credito'].apply(lambda x: x.split('(')[-1].strip(')') if 'Rechazado' in x else 'Aprobado')
df = df.drop('Estado_Credito', axis=1)

# Convertir categóricas a numéricas con one-hot encoding
categorical_cols = ['SISBEN', 'Titulo_Universitario', 'Codeudor', 'Programa', 'Historial_Credito']
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# Eliminar 'Nombre' (no aporta al análisis)
df_encoded = df_encoded.drop('Nombre', axis=1)

print("\nDataFrame limpio (primeras 5 filas):")
print(df_encoded.head())

# --- Análisis exploratorio detallado ---
# 1. Distribución de 'Resultado'
plt.figure(figsize=(8, 5))
sns.countplot(x='Resultado', data=df_encoded)
plt.title('Distribución de Resultado (Aprobado vs Rechazado)')
plt.xlabel('Resultado')
plt.ylabel('Cantidad')
plt.show()
# Explicación: Muestra la cantidad de solicitudes aprobadas vs. rechazadas. Esperamos ~966 "Rechazado" y ~34 "Aprobado",
# destacando un fuerte desbalance que indica criterios de aprobación estrictos.
print("\nConteo de Resultado:")
print(df_encoded['Resultado'].value_counts())

# 2. Distribución de 'Edad' por 'Resultado'
plt.figure(figsize=(10, 6))
sns.boxplot(x='Resultado', y='Edad', data=df_encoded)
plt.title('Distribución de Edad por Resultado')
plt.show()
# Explicación: Compara la distribución de edades entre aprobados y rechazados. Los aprobados probablemente estén entre 18-60
# (mediana ~30-40), mientras que los rechazados incluyen extremos (17, 65+), debido a rechazos por "Edad fuera del rango".
print("\nEstadísticas de Edad por Resultado:")
print(df.groupby('Resultado')['Edad'].describe())

# 3. Relación 'Pruebas_SABER11' y 'Resultado'
plt.figure(figsize=(10, 6))
sns.boxplot(x='Resultado', y='Pruebas_SABER11', data=df_encoded)
plt.title('Puntaje Saber 11 por Resultado')
plt.show()
# Explicación: Muestra cómo los puntajes Saber 11 difieren entre aprobados y rechazados. Los aprobados tendrán una mediana
# más alta (~320-350) frente a ~250-280 para rechazados, reflejando rechazos por "Puntaje Saber 11 bajo".
print("\nEstadísticas de Pruebas_SABER11 por Resultado:")
print(df.groupby('Resultado')['Pruebas_SABER11'].describe())

# 4. Distribución de 'Ingresos_Codeudor' y 'Deudas_Codeudor'
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
sns.histplot(df['Ingresos_Codeudor'], bins=30, kde=True)
plt.title('Distribución de Ingresos del Codeudor')
plt.subplot(1, 2, 2)
sns.histplot(df['Deudas_Codeudor'], bins=30, kde=True)
plt.title('Distribución de Deudas del Codeudor')
plt.tight_layout()
plt.show()
# Explicación: Histogramas que muestran la distribución de ingresos y deudas del codeudor. Ingresos tendrán muchos valores
# entre 0-2M y algunos >4M; deudas entre 0-1M con cola larga. Rechazos por "alta carga financiera" sugieren problemas con deudas altas.

# 5. Motivos de rechazo
plt.figure(figsize=(12, 8))
sns.countplot(y='Motivo', data=df, order=df['Motivo'].value_counts().index)
plt.title('Motivos de Rechazo/Aprobación')
plt.xlabel('Cantidad')
plt.ylabel('Motivo')
plt.show()
# Explicación: Muestra la frecuencia de cada motivo. Los más comunes serán "Tiene ingresos" (~216), "Codeudor con alta carga"
# (~208), y "Sin codeudor válido" (~197). "Aprobado" tendrá solo ~34, indicando múltiples criterios de rechazo.
print("\nConteo de Motivos:")
print(df['Motivo'].value_counts())

# 6. Relación entre 'SISBEN' y 'Resultado'
plt.figure(figsize=(12, 6))
sns.countplot(x='SISBEN', hue='Resultado', data=df)
plt.title('Resultado por Nivel SISBEN')
plt.xticks(rotation=45)
plt.show()
# Explicación: Compara aprobados y rechazados por nivel SISBEN. B1, B2, C1 tendrán más casos; D mostrará pocos/no aprobados
# por "No cumple con SISBEN", sugiriendo que niveles bajos son elegibles.

# 7. Relación entre 'Programa' y 'Resultado'
plt.figure(figsize=(12, 6))
sns.countplot(x='Programa', hue='Resultado', data=df)
plt.title('Resultado por Programa Académico')
plt.xticks(rotation=45)
plt.show()
# Explicación: Muestra aprobados y rechazados por programa. Ingeniería y Enfermería tendrán más solicitudes; algunos rechazos
# por "Programa no elegible" (14 casos) podrían destacar en ciertos programas.

# 8. Correlación entre variables numéricas
numeric_cols = ['Edad', 'Ingresos', 'Ingresos_Codeudor', 'Deudas_Codeudor', 'Pruebas_SABER11', 'Ingresos_Familiares']
plt.figure(figsize=(10, 8))
sns.heatmap(df_encoded[numeric_cols].corr(), annot=True, cmap='coolwarm', vmin=-1, vmax=1)
plt.title('Matriz de Correlación de Variables Numéricas')
plt.show()
# Explicación: Muestra correlaciones entre variables numéricas. Esperamos valores bajos (<0.3), con posible correlación
# moderada (~0.2-0.4) entre 'Ingresos_Codeudor' e 'Ingresos_Familiares', indicando independencia general.

# --- Preprocesamiento para modelado ---
X = df_encoded.drop(['Resultado', 'Motivo'], axis=1)  # Características
y = df_encoded['Resultado'].map({'Aprobado': 1, 'Rechazado': 0})  # Objetivo binario

# Dividir en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Normalizar variables numéricas
scaler = StandardScaler()
X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

# --- Modelado detallado ---
# 1. Regresión Logística
log_model = LogisticRegression(class_weight='balanced', random_state=42)
log_model.fit(X_train, y_train)
y_pred_log = log_model.predict(X_test)

# 2. Random Forest
rf_model = RandomForestClassifier(class_weight='balanced', n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

# --- Evaluación de modelos ---
print("\nReporte de Clasificación - Regresión Logística:")
print(classification_report(y_test, y_pred_log))
print("\nReporte de Clasificación - Random Forest:")
print(classification_report(y_test, y_pred_rf))

# Matrices de confusión
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
sns.heatmap(confusion_matrix(y_test, y_pred_log), annot=True, fmt='d', cmap='Blues')
plt.title('Matriz de Confusión - Regresión Logística')
plt.xlabel('Predicho')
plt.ylabel('Real')
plt.subplot(1, 2, 2)
sns.heatmap(confusion_matrix(y_test, y_pred_rf), annot=True, fmt='d', cmap='Blues')
plt.title('Matriz de Confusión - Random Forest')
plt.xlabel('Predicho')
plt.ylabel('Real')
plt.tight_layout()
plt.show()
# Explicación: Compara predicciones vs. reales. Regresión Logística tendrá muchos Verdaderos Negativos (~190/193 "Rechazado"),
# pocos Verdaderos Positivos (~3-5/7 "Aprobado"). Random Forest mejorará los Verdaderos Positivos, pero el desbalance limita ambos.

# Curva ROC
plt.figure(figsize=(10, 6))
fpr_log, tpr_log, _ = roc_curve(y_test, log_model.predict_proba(X_test)[:, 1])
roc_auc_log = auc(fpr_log, tpr_log)
plt.plot(fpr_log, tpr_log, label=f'Regresión Logística (AUC = {roc_auc_log:.2f})')
fpr_rf, tpr_rf, _ = roc_curve(y_test, rf_model.predict_proba(X_test)[:, 1])
roc_auc_rf = auc(fpr_rf, tpr_rf)
plt.plot(fpr_rf, tpr_rf, label=f'Random Forest (AUC = {roc_auc_rf:.2f})')
plt.plot([0, 1], [0, 1], 'k--')
plt.title('Curva ROC')
plt.xlabel('Tasa de Falsos Positivos')
plt.ylabel('Tasa de Verdaderos Positivos')
plt.legend()
plt.show()
# Explicación: Compara la capacidad de distinguir clases. Regresión Logística tendrá AUC ~0.7-0.8; Random Forest ~0.85-0.9,
# mostrando mejor desempeño, aunque el desbalance evita AUC cercano a 1.

# Validación cruzada
log_cv_scores = cross_val_score(log_model, X, y, cv=5, scoring='f1')
rf_cv_scores = cross_val_score(rf_model, X, y, cv=5, scoring='f1')
print("\nF1-Score promedio (validación cruzada) - Regresión Logística:", log_cv_scores.mean())
print("F1-Score promedio (validación cruzada) - Random Forest:", rf_cv_scores.mean())

# Importancia de características (Random Forest)
importances = rf_model.feature_importances_
feature_names = X.columns
feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances})
feature_importance_df = feature_importance_df.sort_values('Importance', ascending=False)

plt.figure(figsize=(12, 6))
sns.barplot(x='Importance', y='Feature', data=feature_importance_df.head(10))
plt.title('Top 10 Características más Importantes (Random Forest)')
plt.show()
# Explicación: Muestra las 10 variables más influyentes. Esperamos que 'Edad', 'Pruebas_SABER11', 'Ingresos',
# 'Ingresos_Codeudor', y 'Deudas_Codeudor' lideren, reflejando su impacto en la decisión de aprobación/rechazo.