# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10K_kL8mZAbeYtUgHdouGXwiq9u_4vaK3
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans

# Cargar el dataset (ajusta según tu método)
df = pd.read_csv('./dataset_credito.csv')

# --- Ejercicio 1: Clasificación ---
df_clasificacion = df[['Edad', 'Ingresos', 'Ingresos_Codeudor', 'Deudas_Codeudor', 'Pruebas_SABER11', 'Estado_Credito']].copy()
df_clasificacion['Estado_Credito'] = df_clasificacion['Estado_Credito'].apply(lambda x: 1 if x == 'Aprobado' else 0)

X = df_clasificacion[['Edad', 'Ingresos', 'Ingresos_Codeudor', 'Deudas_Codeudor', 'Pruebas_SABER11']]
y = df_clasificacion['Estado_Credito']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

modelo_clasificacion = DecisionTreeClassifier(random_state=42)
modelo_clasificacion.fit(X_train, y_train)
precision = modelo_clasificacion.score(X_test, y_test)
print(f"Ejercicio 1 - Precisión en test: {precision:.2f}")

# --- Ejercicio 2: Regresión ---
df_regresion = df[['Ingresos', 'Ingresos_Codeudor', 'Ingresos_Familiares']]
X_reg = df_regresion[['Ingresos', 'Ingresos_Codeudor']]
y_reg = df_regresion['Ingresos_Familiares']
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X_reg, y_reg, test_size=0.3, random_state=42)

modelo_regresion = LinearRegression()
modelo_regresion.fit(X_train_reg, y_train_reg)
r2 = modelo_regresion.score(X_test_reg, y_test_reg)
print(f"Ejercicio 2 - R² en test: {r2:.2f}")

# --- Ejercicio 3: Agrupamiento ---
df_agrupamiento = df[['Edad', 'Pruebas_SABER11']]
kmeans = KMeans(n_clusters=4, random_state=42)
kmeans.fit(df_agrupamiento)
df_agrupamiento['cluster'] = kmeans.labels_
print("Ejercicio 3 - Agrupamiento completado con 4 clusters.")

# --- Ejercicio  ---
df_cristian = df[['Edad', 'Ingresos_Codeudor']]
kmeans_cristian = KMeans(n_clusters=4, random_state=42)
kmeans_cristian.fit(df_cristian)
df_cristian['cluster'] = kmeans_cristian.labels_
print("Ejercicio 4 - Agrupamiento completado con 4 clusters.")

# ¿Qué factores tienen mayor impacto en la decisión de aprobar o rechazar una solicitud de crédito?
# Verificar datos antes de crear el DataFrame
importances = modelo_clasificacion.feature_importances_
features = X.columns

# Debugging: Imprimir para verificar dimensiones
print("Número de características en X:", len(features))
print("Número de importancias:", len(importances))
print("Características:", features)
print("Importancias:", importances)

# Crear DataFrame con las importancias
feature_importance = pd.DataFrame({'Feature': features, 'Importance': importances})
feature_importance = feature_importance.sort_values('Importance', ascending=False)

# Visualización
plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=feature_importance)
plt.title('Importancia de las Características en la Aprobación del Crédito')
plt.show()

print("Pregunta 1: Los factores con mayor impacto son:")
print(feature_importance)

# --- Trabajo Final: Pregunta 2 ---
df['Estado_Credito_Binario'] = df['Estado_Credito'].apply(lambda x: 1 if x == 'Aprobado' else 0)
X_log = df[['Ingresos']]
y_log = df['Estado_Credito_Binario']

modelo_logistico = LogisticRegression()
modelo_logistico.fit(X_log, y_log)
probabilidad = modelo_logistico.predict_proba([[1000000]])[0][1]

plt.figure(figsize=(10, 6))
sns.boxplot(x='Estado_Credito_Binario', y='Ingresos', data=df)
plt.title('Ingresos por Estado del Crédito')
plt.show()

print(f"Pregunta 2: Probabilidad de aprobación con ingresos de 1M: {probabilidad:.2f}")
print("Los solicitantes con ingresos bajos tienen mayor probabilidad de aprobación.")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder
from yellowbrick.cluster import KElbowVisualizer
from sklearn.ensemble import RandomForestClassifier

# Configuración general
sns.set_palette('viridis')  # Configuración de paleta de colores con Seaborn

# --- Carga y preprocesamiento inicial ---
df = pd.read_csv('./dataset_credito.csv')
df['Estado_Credito_Binario'] = df['Estado_Credito'].apply(lambda x: 1 if x == 'Aprobado' else 0)
df.to_csv('estudiantes_credito_procesado.csv', index=False)

df.head(20)

# Exploración inicial
print("Primeras 5 filas:\n", df.head())
print("\nInformación:\n", df.info())
print("\nEstadísticas descriptivas:\n", df.describe())
print("\nDistribución de Estado_Credito:\n", df['Estado_Credito'].value_counts())
print("\nValores nulos:\n", df.isnull().sum())

# --- Clasificación 1: Edad, Ingresos_Codeudor, Pruebas_SABER11 ---
df_clas1 = df[['Edad', 'Ingresos_Codeudor', 'Pruebas_SABER11', 'Estado_Credito_Binario']]
X_clas1 = df_clas1.drop('Estado_Credito_Binario', axis=1)
y_clas1 = df_clas1['Estado_Credito_Binario']
X_train_clas1, X_test_clas1, y_train_clas1, y_test_clas1 = train_test_split(X_clas1, y_clas1, test_size=0.3, random_state=42)

modelo_clas1 = DecisionTreeClassifier(random_state=42)
modelo_clas1.fit(X_train_clas1, y_train_clas1)
precision_clas1 = modelo_clas1.score(X_test_clas1, y_test_clas1)
print(f"\nClasificación 1 - Precisión: {precision_clas1:.2f}")
print(f"Pregunta: ¿Cómo saber si un crédito será aprobado con Edad, Ingresos_Codeudor y SABER 11?")
print(f"Respuesta: Precisión del modelo: {precision_clas1:.2f}")
df_clas1.to_csv('datos_clasificacion1.csv', index=False)

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df_clas1, x='Edad', y='Ingresos_Codeudor', hue='Estado_Credito_Binario', size='Pruebas_SABER11')
plt.title('Edad vs Ingresos_Codeudor por Estado del Crédito')
plt.show()

# --- Clasificación 2: Más variables ---
df_clas2 = df[['Edad', 'Ingresos', 'Ingresos_Codeudor', 'Deudas_Codeudor', 'Pruebas_SABER11', 'Estado_Credito_Binario']]
X_clas2 = df_clas2.drop('Estado_Credito_Binario', axis=1)
y_clas2 = df_clas2['Estado_Credito_Binario']
X_train_clas2, X_test_clas2, y_train_clas2, y_test_clas2 = train_test_split(X_clas2, y_clas2, test_size=0.3, random_state=42)

modelo_clas2 = DecisionTreeClassifier(random_state=42)
modelo_clas2.fit(X_train_clas2, y_train_clas2)
precision_clas2 = modelo_clas2.score(X_test_clas2, y_test_clas2)
print(f"\nClasificación 2 - Precisión: {precision_clas2:.2f}")
print(f"Pregunta: ¿Cómo predecir aprobación con más variables?")
print(f"Respuesta: Precisión: {precision_clas2:.2f}")
df_clas2.to_csv('datos_clasificacion2.csv', index=False)

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df_clas2, x='Ingresos', y='Deudas_Codeudor', hue='Estado_Credito_Binario')
plt.title('Ingresos vs Deudas_Codeudor por Estado del Crédito')
plt.show()

# Importancia de características
feature_importance = pd.DataFrame({'Feature': X_clas2.columns, 'Importance': modelo_clas2.feature_importances_}).sort_values('Importance', ascending=False)
plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=feature_importance)
plt.title('Importancia de Características en Aprobación')
plt.show()
print("Factores con mayor impacto:\n", feature_importance)

# --- Regresión: Ingresos_Familiares vs Ingresos_Codeudor ---
df_reg = df[['Ingresos_Codeudor', 'Ingresos_Familiares']]
X_reg = df_reg[['Ingresos_Codeudor']]
y_reg = df_reg['Ingresos_Familiares']
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X_reg, y_reg, test_size=0.3, random_state=42)

modelo_reg = LinearRegression()
modelo_reg.fit(X_train_reg, y_train_reg)
r2_reg = modelo_reg.score(X_test_reg, y_test_reg)
prediccion = modelo_reg.predict([[1000000]])
print(f"\nRegresión - R²: {r2_reg:.2f}")
print(f"Pregunta: ¿Cuál es el ingreso familiar según Ingresos_Codeudor?")
print(f"Respuesta: R²: {r2_reg:.2f}. Ejemplo (1M): {prediccion[0]:.2f}")
df_reg.to_csv('datos_regresion.csv', index=False)

plt.figure(figsize=(10, 6))
plt.scatter(df_reg['Ingresos_Codeudor'], df_reg['Ingresos_Familiares'])
plt.title('Ingresos Familiares vs Ingresos_Codeudor')
plt.xlabel('Ingresos_Codeudor')
plt.ylabel('Ingresos_Familiares')
plt.show()

# --- Agrupamiento 1: Edad vs Pruebas_SABER11 ---
df_agr1 = df[['Edad', 'Pruebas_SABER11']]
visualizer = KElbowVisualizer(KMeans(random_state=42), k=(2, 10))
visualizer.fit(df_agr1)
visualizer.show()

kmeans_agr1 = KMeans(n_clusters=3, random_state=42)
kmeans_agr1.fit(df_agr1)
df_agr1['Cluster'] = kmeans_agr1.labels_
print("\nAgrupamiento 1 - 3 clusters:")
print("- Cluster 0: Jóvenes con puntajes altos.")
print("- Cluster 1: Adultos con puntajes medios.")
print("- Cluster 2: Mayores con puntajes bajos.")
df_agr1.to_csv('datos_agrupamiento1.csv', index=False)

plt.figure(figsize=(10, 6))
plt.scatter(df_agr1['Edad'], df_agr1['Pruebas_SABER11'], c=df_agr1['Cluster'], cmap='viridis')
plt.title('Grupos: Edad vs Pruebas_SABER11')
plt.xlabel('Edad')
plt.ylabel('Pruebas_SABER11')
plt.show()

# --- Agrupamiento 2: Edad vs Ingresos_Familiares ---
df_agr2 = df[['Edad', 'Ingresos_Familiares']]
visualizer.fit(df_agr2)
visualizer.show()

kmeans_agr2 = KMeans(n_clusters=4, random_state=42)
kmeans_agr2.fit(df_agr2)
df_agr2['Cluster'] = kmeans_agr2.labels_
print("\nAgrupamiento 2 - 4 clusters:")
print("- Cluster 0: Jóvenes con ingresos bajos.")
print("- Cluster 1: Adultos con ingresos medios.")
print("- Cluster 2: Mayores con ingresos altos.")
print("- Cluster 3: Atípicos con ingresos muy altos.")
df_agr2.to_csv('datos_agrupamiento2.csv', index=False)

plt.figure(figsize=(10, 6))
plt.scatter(df_agr2['Edad'], df_agr2['Ingresos_Familiares'], c=df_agr2['Cluster'], cmap='viridis')
plt.title('Grupos: Edad vs Ingresos_Familiares')
plt.xlabel('Edad')
plt.ylabel('Ingresos_Familiares')
plt.show()

# --- Agrupamiento 3: Edad vs Ingresos_Codeudor ---
df_agr3 = df[['Edad', 'Ingresos_Codeudor']]
visualizer.fit(df_agr3)
visualizer.show()

kmeans_agr3 = KMeans(n_clusters=4, random_state=42)
kmeans_agr3.fit(df_agr3)
df_agr3['Cluster'] = kmeans_agr3.labels_
print("\nAgrupamiento 3 - 4 clusters:")
print("- Cluster 0: Jóvenes con ingresos bajos del codeudor.")
print("- Cluster 1: Adultos con ingresos medios del codeudor.")
print("- Cluster 2: Jóvenes con ingresos altos del codeudor.")
print("- Cluster 3: Adultos mayores con ingresos variables.")
df_agr3.to_csv('datos_agrupamiento3.csv', index=False)

plt.figure(figsize=(10, 6))
plt.scatter(df_agr3['Edad'], df_agr3['Ingresos_Codeudor'], c=df_agr3['Cluster'], cmap='viridis')
plt.title('Grupos: Edad vs Ingresos_Codeudor')
plt.xlabel('Edad')
plt.ylabel('Ingresos_Codeudor')
plt.show()

# --- Modelo Logístico ---
df_log = df[['Ingresos', 'Estado_Credito_Binario']]
X_log = df_log[['Ingresos']]
y_log = df_log['Estado_Credito_Binario']
modelo_log = LogisticRegression()
modelo_log.fit(X_log, y_log)
prob = modelo_log.predict_proba([[1000000]])[0][1]
print(f"\nModelo Logístico - Probabilidad (1M ingresos): {prob:.2f}")

rangos_ingresos = np.linspace(df_log['Ingresos'].min(), df_log['Ingresos'].max(), 100).reshape(-1, 1)
probabilidades = modelo_log.predict_proba(rangos_ingresos)[:, 1]
plt.figure(figsize=(12, 6))
plt.plot(rangos_ingresos, probabilidades, color='darkorange', lw=3)
plt.scatter(df_log['Ingresos'], df_log['Estado_Credito_Binario'], alpha=0.7, edgecolor='k')
plt.title('Probabilidad de Aprobación vs Ingresos')
plt.xlabel('Ingresos')
plt.ylabel('Probabilidad')
plt.grid(linestyle='--', alpha=0.5)
plt.show()

# --- Perfil de Riesgo ---
df_perfil = df[['Edad', 'Ingresos', 'Pruebas_SABER11', 'Historial_Credito']]
df_perfil['Riesgo'] = df_perfil['Historial_Credito'].apply(lambda x: 1 if x == 'Malo' else 0)
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df_perfil, x='Edad', y='Ingresos', hue='Riesgo', size='Pruebas_SABER11')
plt.title('Perfiles de Riesgo: Edad, Ingresos y SABER 11')
plt.show()
print("Características promedio por riesgo:\n", df_perfil[['Edad', 'Ingresos', 'Pruebas_SABER11', 'Riesgo']].groupby('Riesgo').mean())

# --- Agrupamiento con todas las variables categóricas codificadas ---
df_cluster = df.drop(columns=['Nombre'])
label_cols = df_cluster.select_dtypes(include='object').columns
label_encoders = {col: LabelEncoder() for col in label_cols}
for col in label_cols:
    df_cluster[col] = label_encoders[col].fit_transform(df_cluster[col])

kmeans_all = KMeans(n_clusters=2, random_state=42)
df_cluster['Cluster'] = kmeans_all.fit_predict(df_cluster.drop(columns=['Estado_Credito']))
df_comparacion = pd.concat([df['Estado_Credito'], df_cluster['Cluster']], axis=1)
df_comparacion['Estado_Simplificado'] = df_comparacion['Estado_Credito'].apply(lambda x: 'Aprobado' if 'Aprobado' in x else 'Rechazado')
distribucion_grupos = pd.crosstab(df_comparacion['Estado_Simplificado'], df_comparacion['Cluster'], margins=True)
print("\nDistribución por grupos (2 clusters):\n", distribucion_grupos)

y_log.unique()